CodingEvents/Models/ErrorViewModel.cs
using System;

namespace CodingEvents.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CodingEvents/Models/Event.cs
using System;
namespace CodingEvents.Models
{
    public class Event
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime Date { get; set; }
        public string ContactEmail { get; set; }
        public int Id { get; set; }

        public Event()
        {
        }

        public Event(string name, string description, DateTime date)
        {
            Name = name;
            Description = description;
            Date = date;
            ContactEmail = ContactEmail;
        }


        public override string ToString()
        {
            return Name;
        }

        public override bool Equals(object obj)
        {
            return obj is Event @event &&
                   Id == @event.Id;
        }

        public override int GetHashCode()
        {
            return HashCode.Combine(Id);
        }
    }
}

CodingEvents/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CodingEvents.Data;
using CodingEvents.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CodingEvents.Controllers
{
    public class EventsController : Controller
    {
        //static private List<string> Events = new List<string>();
        //static private Dictionary<string, string> Events = new Dictionary<string, string>();
        //static private List <Event> Events = new List<Event>();

        // GET: /<controller>/
        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.events = EventData.GetAll();

            return View();
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [Route("/Events/Add")]
        public IActionResult NewEvent(Event newEvent)
        {
            EventData.Add(newEvent);

            return Redirect("/Events");
        }

        public IActionResult Delete()
        {
            ViewBag.events = EventData.GetAll();
            return View();
        }

        [HttpPost]

        public IActionResult Delete(int[] eventIds)
        {
            foreach(int eventId in eventIds)
            {
                EventData.Remove(eventId);
            }

            return Redirect("/Events");
        }

        [HttpGet]
        [Route("Events/Edit/{eventId}")]
        public IActionResult Edit(int eventId)
        {
            Event eventToEdit =EventData.GetById(eventId);
            ViewBag.eventToEdit = eventToEdit;
            ViewBag.title = $"Editing {eventToEdit.Name} (ID={eventToEdit.Id})";
            return Redirect("/Events");
        }

        [HttpPost]
        [Route("/Events/Edit")]
        public IActionResult SubmitEditEventForm(int eventId, string name, string description)
        {
            Event edittedEvent = EventData.GetById(eventId);
            edittedEvent.Name = name;
            edittedEvent.Description = description;
            return Redirect("/Events");
        }

    }
}

CodingEvents/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CodingEvents.Models;

namespace CodingEvents.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CodingEvents/Views/Events/Add.cshtml
<h1>Add Event</h1>

<form method="post">
    <input name="name" type="text" autocomplete="off" placeholder="Enter event name..." />
    <br />
    <br />
    <input name="description" type="text" placeholder="Enter event description..." autocomplete="off" />
    <br />
    <br />
    <input name="date" type="datetime-local" aria-describedby="date-format" min="2022-01-01" max="2032-01-01" />
    <br />
    <br />
    <input name="email" type="email" placeholder="Enter contact's email" autocomplete="off"/>
    <br />
    <br />
    <input type="submit" value="Add Event" />
</form>

<partial name="/Views/Shared/_LinkListPartial.cshtml" />

CodingEvents/Views/Events/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<h1>Delete Events</h1>

@if (ViewBag.events.Count == 0)
{
    <p>No events yet!</p>
}
<form method="post">
    @foreach (var evt in ViewBag.events)
    {
        <div class="form-group">
            <label>
                <span>@evt.Name</span>
                <input type="checkbox" value="@evt.Id" name="eventIds" />
            </label>
        </div>
    }
    <input type="submit" value="Delete Selected Events" class="btn btn-danger">
</form>

CodingEvents/Views/Events/Edit.cshtml
<h1>Edit Event</h1>

<form method="post" action="/events/edit">
    <input type="hidden" value="@ViewBag.eventToEdit.Id" name="eventId" />
    <input name="name" value="@ViewBag.eventToEdit.Name" type="text" autocomplete="off" placeholder="Enter event name..." />
    <br />
    <br />
    <input name="description" value="@ViewBag.eventToEdit.Description" type="text" placeholder="Enter event description..." autocomplete="off" />
    <br />
    <br />
    <input name="date" value="@ViewBag.eventToEdit.Date" type="datetime-local" aria-describedby="date-format" min="2022-01-01" max="2032-01-01" />
    <br />
    <br />
    <input name="email" value="@ViewBag.eventToEdit.ContactEmail" type="email" placeholder="Enter contact's email" autocomplete="off"/>
    <br />
    <br />
    <input type="submit" value="Save Edits" />
</form>

<partial name="/Views/Shared/_LinkListPartial.cshtml" />

CodingEvents/Views/Events/Index.cshtml
<h1>Coding Events</h1>

<p>
    <a asp-controller="Events" asp-action="Add">Add Event</a>
</p>
<p>
    <a asp-controller="Events" asp-action="Delete">Delete Events</a>
</p>
<p>
    <a asp-controller="Events" asp-action="Edit">Edit Events</a>
</p>


@if (ViewBag.events.Count == 0)
{
    <p>No events yet!</p>
}

@*<ul>
        @foreach (string meeting in ViewBag.events)
         {
            <li>@meeting</li>
         }
    </ul>*@

@*<ul>
        @foreach (KeyValuePair<string,string> kvp in ViewBag.events)
         {
            <li>@kvp.Key: @kvp.Value</li> 
         }
</ul>*@

@* make name column and description column
    *@

<table class="table">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Description</th>
            <th>Date</th>
        </tr>
        @foreach (var evt in ViewBag.events)
        {
<tr>
    <td>@evt.Id</td>
    <td>@evt.Name</td>
    <td>@evt.Description</td>
    <td>@evt.Date</td>
    <td><a asp-controller="Events" asp-action="Edit" asp-route-id="@evt.Id">Edit Event</a></td>
</tr>
        }
</table>

CodingEvents/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CodingEvents/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CodingEvents</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CodingEvents</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Events" asp-action="Index">Events</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Events" asp-action="Add">Add Event</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CodingEvents - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

CodingEvents/Views/Shared/_LinkListPartial.cshtml
<br />
<br />
<br />
<br />
<br />
<br />
<a href="https://www.launchcode.org">LaunchCode</a>
<br />
<a href="https://www.lego.com">Play Well</a>
<br />
<a href="https://www.webelements.com">Other Building Blocks</a>